### ISSUE TITLE
Task - WebApp UX - Target Audience

### ISSUE THREAD

**Issue by tylerhearon** [the-to-do-list/the-to-do-list-BASE-repository#2]
# Task - WebApp UX
### Target Audience

- [x]  Expand introductory paragraph - Tyler
- [x]  Persona 1 - Student - JM
- [x]  Persona 2 - Working Professional - Tyler
