### ISSUE TITLE
Task - WebApp UX - Visual Design

### ISSUE THREAD

**Issue by tylerhearon** [the-to-do-list/the-to-do-list-BASE-repository#6]
# Task - WebApp UX
### Visual Design

- [x]  Font Selection - Qian
- [x]  General Colour Selection - Qian
- [x]  Basic UX and Color Relationship - Qian
