### ISSUE TITLE
Task - WebApp UX - Wireframe Sketches

### ISSUE THREAD

**Issue by tylerhearon** [the-to-do-list/the-to-do-list-BASE-repository#7]
# Task - WebApp UX
##### Wireframes
- [x]  Home Page - Qian
- [x]  Task Page - Qian
- [x]  Profile Page - Qian
